version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@ygligttfh1zhpfwa_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=admin
      - spring.datasource.password=Oraclecloud123
    restart: always